FROM node:14.17-alpine as builder

WORKDIR /app/client

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.21.1-alpine

COPY --from=builder /app/client/build /usr/share/nginx/html

COPY --from=builder /app/client/nginx.conf /etc/nginx/conf.d

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]