services:
  client:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      EXPRESS_HOST: http://localhost
      EXPRESS_PORT: 5000
      REACT_APP_API_URL: http://localhost:5000/api
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    # Due to react-scripts bug https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true

  server:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - '5000:5000'
    env_file:
      - ./server/development.env
    environment:
      NODE_ENV: development
      HOST: http://localhost
      PORT: 5000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
