export const VALIDATE_SHIPPING_FAILED = 'VALIDATE_SHIPPING_FAILED';
export const VALIDATE_SHIPPING_SUCCESS = 'VALIDATE_SHIPPING_SUCCESS';

export const VALIDATE_PAYMENT_FAILED = 'VALIDATE_PAYMENT_FAILED';
export const VALIDATE_PAYMENT_SUCCESS = 'VALIDATE_PAYMENT_SUCCESS';

export const REMOVE_SELECTED_SHIPPING = 'REMOVE_SELECTED_SHIPPING';
export const REMOVE_SELECTED_PAYMENT = 'REMOVE_SELECTED_PAYMENT';
