export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAILURE = 'ORDER_DETAILS_FAILURE';

export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILURE = 'PLACE_ORDER_FAILURE';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAILURE = 'ORDER_LIST_FAILURE';

export const USER_ORDER_LIST_REQUEST = 'USER_ORDER_LIST_REQUEST';
export const USER_ORDER_LIST_SUCCESS = 'USER_ORDER_LIST_SUCCESS';
export const USER_ORDER_LIST_FAILURE = 'USER_ORDER_LIST_FAILURE';

export const PRODUCT_ORDER_LIST_REQUEST = 'PRODUCT_ORDER_LIST_REQUEST';
export const PRODUCT_ORDER_LIST_SUCCESS = 'PRODUCT_ORDER_LIST_SUCCESS';
export const PRODUCT_ORDER_LIST_FAILURE = 'PRODUCT_ORDER_LIST_FAILURE';

export const PRODUCT_ORDER_BY_USER_REQUEST = 'PRODUCT_ORDER_BY_USER_REQUEST';
export const PRODUCT_ORDER_BY_USER_SUCCESS = 'PRODUCT_ORDER_BY_USER_SUCCESS';
export const PRODUCT_ORDER_BY_USER_FAILURE = 'PRODUCT_ORDER_BY_USER_FAILURE';

export const UPDATE_ORDER_ISDELIVERED_REQUEST =
  'UPDATE_ORDER_ISDELIVERED_REQUEST';
export const UPDATE_ORDER_ISDELIVERED_SUCCESS =
  'UPDATE_ORDER_ISDELIVERED_SUCCESS';
export const UPDATE_ORDER_ISDELIVERED_FAILURE =
  'UPDATE_ORDER_ISDELIVERED_FAILURE';
