// ----- PAYMENT -------
export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST';
export const PAYMENT_METHODS_SUCCESS = 'PAYMENT_METHODS_SUCCESS';
export const PAYMENT_METHODS_FAILURE = 'PAYMENT_METHODS_FAILURE';

export const SAVE_PAYMENT_REQUEST = 'SAVE_PAYMENT_REQUEST';
export const SAVE_PAYMENT_SUCCESS = 'SAVE_PAYMENT_SUCCESS';
export const SAVE_PAYMENT_FAILURE = 'SAVE_PAYMENT_FAILURE';

export const REMOVE_PAYMENT_REQUEST = 'REMOVE_PAYMENT_REQUEST';
export const REMOVE_PAYMENT_SUCCESS = 'REMOVE_PAYMENT_SUCCESS';
export const REMOVE_PAYMENT_FAILURE = 'REMOVE_PAYMENT_FAILURE';

export const REMOVE_ALL_PAYMENT = 'REMOVE_ALL_PAYMENT';
// ------------ X ------------
