export const PRODUCT_REVIEW_REQUEST = 'PRODUCT_REVIEW_REQUEST';
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS';
export const PRODUCT_REVIEW_FAILURE = 'PRODUCT_REVIEW_FAILURE';

export const USER_REVIEW_REQUEST = 'USER_REVIEW_REQUEST';
export const USER_REVIEW_SUCCESS = 'USER_REVIEW_SUCCESS';
export const USER_REVIEW_FAILURE = 'USER_REVIEW_FAILURE';

export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATE_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATE_FAILURE = 'REVIEW_CREATE_FAILURE';

export const REVIEW_DELETE_REQUEST = 'REVIEW_DELETE_REQUEST';
export const REVIEW_DELETE_SUCCESS = 'REVIEW_DELETE_SUCCESS';
export const REVIEW_DELETE_FAILURE = 'REVIEW_DELETE_FAILURE';
