// ----- SHIPPING -------
export const SHIPPING_ADDRESSES_REQUEST = 'SHIPPING_ADDRESSES_REQUEST';
export const SHIPPING_ADDRESSES_SUCCESS = 'SHIPPING_ADDRESSES_SUCCESS';
export const SHIPPING_ADDRESSES_FAILURE = 'SHIPPING_ADDRESSES_FAILURE';

export const SAVE_SHIPPING_REQUEST = 'SAVE_SHIPPING_REQUEST';
export const SAVE_SHIPPING_SUCCESS = 'SAVE_SHIPPING_SUCCESS';
export const SAVE_SHIPPING_FAILURE = 'SAVE_SHIPPING_FAILURE';

export const EDIT_SHIPPING_REQUEST = 'EDIT_SHIPPING_REQUEST';
export const EDIT_SHIPPING_SUCCESS = 'EDIT_SHIPPING_SUCCESS';
export const EDIT_SHIPPING_FAILURE = 'EDIT_SHIPPING_FAILURE';

export const REMOVE_SHIPPING_REQUEST = 'REMOVE_SHIPPING_REQUEST';
export const REMOVE_SHIPPING_SUCCESS = 'REMOVE_SHIPPING_SUCCESS';
export const REMOVE_SHIPPING_FAILURE = 'REMOVE_SHIPPING_FAILURE';

export const REMOVE_ALL_SHIPPING = 'REMOVE_ALL_SHIPPING';
// ------------ X ------------
