export const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const USER_CHANGED_NAME = 'USER_CHANGED_NAME';
export const REMOVE_UPDATED_USER = 'REMOVE_UPDATED_USER';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';

export const USER_UPDATE_BYADMIN_REQUEST = 'USER_UPDATE_BYADMIN_REQUEST';
export const USER_UPDATE_BYADMIN_SUCCESS = 'USER_UPDATE_BYADMIN_SUCCESS';
export const USER_UPDATE_BYADMIN_FAILURE = 'USER_UPDATE_BYADMIN_FAILURE';
